### ISSUE TITLE
Minify and concatenate JS files into one file

### ISSUE THREAD

**Issue by sahibjotsaggu** [sahibjotsaggu/howacomputerworks#21]
Make four pull requests to receive a free shirt.

**Comment by unluisco** [comment]
Can I take this?

**Comment by sahibjotsaggu** [comment]
Yes. Thanks.

**Comment by unluisco** [comment]
the task is to minify each JS file in the repository? and leave the originals
and where should I change the links to those new minify js?

**Comment by sahibjotsaggu** [comment]
Actually, I wrote it incorrectly. I would like to Minify the files and concatenate them all into one file. I would prefer using Gulp.js

**Comment by sagarchoudhary96** [comment]
@sahibjotsaggu   i can work on it

**Comment by sagarchoudhary96** [comment]
@sahibjotsaggu u want to minify all the js files present in the repo or some specific folder?

**Comment by sahibjotsaggu** [comment]
@sagarchoudhary96 Yes, all JS files that are there.

**Comment by interwho** [comment]
@sahibjotsaggu tfw 2 people take it and it never gets done

**Comment by sahibjotsaggu** [comment]
@interwho maybe it's impossible! 😢

**Comment by miazima** [comment]
Check out my pull request :)

**Comment by sahibjotsaggu** [comment]
@miazima Looks good! Great work!
